### ISSUE TITLE
Bug: [Columns] Tabbed Block is Broken

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-volvotrucks-us#645] opened 2024-05-22 13:24 UTC
### Issue Type

Bug

### Summary

[columns] [tabbed-carousel] is broken on Volvo USA and Canadian (FR and EN) websites

### Priority

High

### Description

The columns tabbed block is no longer working as expected. The tabs are not visible where the user clicks on the tab to reveal the associated text and imagery content. Now it is displaying all of the content as plain text and images vertically top to bottom on the page. 

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All browsers and devices

### Steps to Reproduce

1. Navigate to USA - https://www.volvotrucks.us/parts-and-services/parts/genuine/engine/ 
2. Navigate to CA English - https://www.volvotrucks.ca/en-ca/parts-and-services/parts/genuine/engine
3. Navigate to CA French - https://www.volvotrucks.ca/en-ca/parts-and-services/parts/genuine/engine
4. See the block under "Genuine Cooling" is broken 

Affected pages on VT US:
1. https://www.volvotrucks.us/trucks/vnl/
2. https://www.volvotrucks.us/trucks/vnl/exterior/
3. https://www.volvotrucks.us/trucks/vnr/exterior/
4. https://www.volvotrucks.us/trucks/vnl/interior/
5. https://www.volvotrucks.us/innovation/electromobility/
6. https://www.volvotrucks.us/trucks/vhd/interior/
7. https://www.volvotrucks.us/trucks/vnx/exterior/
8. https://www.volvotrucks.us/trucks/vnx/performance/
9. https://www.volvotrucks.us/trucks/vnx/features/
10. https://www.volvotrucks.us/trucks/vnr/interior/
11. https://www.volvotrucks.us/trucks/vnx/interior/
12. https://www.volvotrucks.us/trucks/vnr/features/
13. https://www.volvotrucks.us/trucks/vah/features/
14. https://www.volvotrucks.us/trucks/vnl/features/
15. https://www.volvotrucks.us/trucks/vnr-electric/
16. https://www.volvotrucks.us/trucks/vhd/exterior/
17. https://www.volvotrucks.us/trucks/vhd/features/
18. https://www.volvotrucks.us/parts-and-services/parts/remanufactured/engine/
19. https://www.volvotrucks.us/parts-and-services/parts/genuine/engine/
20. https://www.volvotrucks.us/purchasing-a-truck/volvo-certified/

### Expected Results

![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/bd9d14cf-b7e8-4a1a-854d-52e597f9f48d)

### Actual Results

![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/1a0dc5a8-a4a6-4f90-a22a-f9b89e46a0ab)

**Comment by ZoeBeykirch** [comment] 2024-05-22 19:11
@cogniSyb Thanks for looking into this! Let's talk about the [v2-tabbed-carousel] of Mack Trucks solution tomorrow in standup/refinement - the Volvo redesigned PDPs are still in progress, but if this bug fix would require getting all those pages updated to the new redesign it would likely motivate that work to happen faster.

**Comment by BeckyMedlin** [comment] 2024-05-23 15:13
@cogniSyb @verareljic @mollyaljenkins We need to determine root cause of this issue. Please document it here. If this block broke as a result of the Helix5 upgrade, we need to provide feedback to Darin at Adobe.

**Comment by verareljic** [comment] 2024-05-24 12:36
@ZoeBeykirch please follow up with @williebender and update the ticket. Thanks.

**Comment by girishdigrajkar** [comment] 2024-06-12 11:58
**Observation:**
**Mobile :** 
1.  https://645-tabbed-carousel--vg-volvotrucks-us--hlxsites.aem.page/drafts/syb/block/v2-tabbed-carousel-v1-page.  as soon as you click on second tab the slight of third tab is displayed in V2 page however, not the case with this V1 page - needs to be addressed  ( It is occurring for first image variant)
2. For image variant above click on second tab and then scroll of image is not smooth ...especially observe at the end the image scrolls fast to left corner all of sudden

<img width="1728" alt="Screenshot 2024-06-12 at 2 57 13 PM" src="https://github.com/hlxsites/vg-volvotrucks-us/assets/125972657/7277c799-09b2-4393-970b-4bdc7adb8237">

**Comment by girishdigrajkar** [comment] 2024-06-13 10:49
For point 1 : https://github.com/hlxsites/vg-macktrucks-com/issues/706 will address it so taking out of scope from this ticket (discussed with Syb)  cc: @mollyaljenkins 
For Point 2: Able to get the desired results 

Hence, Closing the issue.

**Closed by girishdigrajkar** 2024-06-13 10:49 UTC
Labels: bugfix, Spillover, 24B, OPS support
