### ISSUE TITLE
Template: Magazine Article - Article Content

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-volvotrucks-us#555] opened 2024-02-20 15:18 UTC
From vg-volvotrucks-us-rd created by [DanielaPedrochevd](https://github.com/DanielaPedrochevd): Netcentric/vg-volvotrucks-us-rd#188  

**Agile Requirement**
As a business owner, I want to display an article embedded in a page so that when users click on the article they can read it.

**Comment by ZoeBeykirch** [comment] 2024-04-26 19:45
Closing this ticket because it is a duplicate of https://github.com/hlxsites/vg-volvotrucks-us/issues/560

**Closed by ZoeBeykirch** 2024-04-26 19:45 UTC
Labels: SRB, Magazine
