### ISSUE TITLE
Defect: Minimal: Getting js error in console 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#137] opened 2023-03-21 07:28 UTC
Steps:
1. Navigate to https://navigation-stickiness--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr-electric/   or 
https://navigation-stickiness--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr-electric/
2. Validate the console for errors

Actual:
Getting js error in console
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/226540968-975de4c9-7208-40ac-833c-fce86168197b.png">

**Comment by bpauli** [comment] 2023-03-21 09:36
I don't think that we can fix this as this request is done by the OneTrust script and needs to be fixed on OT side. Btw. the issue is also currently existing on the https://volvotrucks.us site.

**Closed** 2023-04-18 02:24 UTC
Labels: bug
